# Site settings
title: iOS/Android [ChaosOverFlow]
email: your-email@domain.com
description: >
  iOS Android ChaosOverFlow Chat room site.
baseurl: "/iOSAndroidChaosOverFlow"
url: "http://alexcarpenter.me"
fixedNav: 'true' # true or false
theme: grey # green, blue, orange, purple, grey
twitterUsername: 
githubUsername: 
dribbbleUsername:
codepenUsername:

# Build settings
permalink: /:year/:month/:title
markdown: kramdown
include: [_pages]
exclude: [_site, CHANGELOG.md, LICENSE, README.md]
sass:
  style: compressed

comments :
    provider : disqus
    disqus :
      short_name : Admin
    livefyre :
      site_id : 123
    intensedebate :
      account : 123abc
    facebook :
      appid : 123
      num_posts: 5
      width: 580
      colorscheme: light
    duoshuo :
      short_name : Admin